const teamNames = {
  Arsenal: "Arsenal",
  "Aston Villa": "Astone Villa",
  Bournemouth: "Bournemouth",
  "Brighton and Hove Albion": "Brighton",
  Burnley: "Burnley",
  Brentford: "Brentford",
  "Cardiff City": "Cardiff",
  Chelsea: "Chelsea",
  "Crystal Palace": "Crystal Palace",
  Everton: "Everton",
  Fulham: "Fulham",
  "Huddersfield Town": "Huddersfield",
  "Leeds United": "Leeds",
  "Leicester City": "Leicester",
  Liverpool: "Liverpool",
  "Manchester City": "Man City",
  "Manchester United": "Man Utd",
  "Newcastle United": "Newcastle",
  "Norwich City": "Norwich",
  "Sheffield United": "Sheffield",
  Southampton: "Southampton",
  "Tottenham Hotspur": "Spurs",
  Watford: "Watford",
  "West Ham United": "West Ham",
  "Wolverhampton Wanderers": "Wolves",
};

export default teamNames